version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .deployment/Dockerfile
    container_name: tasky
    restart: unless-stopped
    env_file:
      - ../.env.docker
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ../:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  postgres:
    image: postgres:15-alpine
    container_name: tasky_db
    restart: unless-stopped
    env_file:
      - ../.env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: